name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - docker-github-actions
  pull_request:
    branches:
      - docker-github-actions

jobs:
  build-push-image:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Correctly using an action

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  # Correctly using an action
        with:
          aws-region: 'us-east-1'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v2  # Correctly using an action

      - name: Set short git commit SHA
        id: short-sha
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV  # Using run for shell command

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: 116981805219.dkr.ecr.us-east-1.amazonaws.com
          REPOSITORY: capstone-2
          IMAGE_TAG: ${{ env.COMMIT_SHORT_SHA }}  # Using environment variable set earlier
        run: |
          # Build Docker image
          docker build -t github-actions-repo .
          
          # Tag Docker image with commit SHA and latest tag
          docker tag github-actions-repo:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker tag github-actions-repo:latest $REGISTRY/$REPOSITORY:latest
          
          # Push the image to ECR with both tags
          docker push --all-tags $REGISTRY/$REPOSITORY
