name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
       - staging
       - main
jobs:
  build-push-image:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v2  

      - name: Set short git commit SHA
        id: short-sha
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV

      - name: Determine Environment and Image Tag
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "DEPLOYMENT_ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOYMENT_ENV=production" >> $GITHUB_ENV
          else
            echo "DEPLOYMENT_ENV=dev" >> $GITHUB_ENV
          fi
          
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: 116981805219.dkr.ecr.us-east-1.amazonaws.com
          REPOSITORY: capstone-2
          IMAGE_TAG: ${{ env.COMMIT_SHORT_SHA }}-${{ env.DEPLOYMENT_ENV }}  # Dynamic tagging
        run: |
          docker build -t github-actions-repo .
          docker tag github-actions-repo:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker tag github-actions-repo:latest $REGISTRY/$REPOSITORY:latest
          docker push --all-tags $REGISTRY/$REPOSITORY