name: Docker Build and Deploy to Amazon ECR

on:
  push:
    branches:
      - Dev
      - Stage
      - Main
  pull_request:
    branches:
      - Dev
      - Stage
      - Main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, stage, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS credentials for ${{ matrix.environment }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets['AWS_ACCESS_KEY_ID_' + matrix.environment | upper] }}
          aws-secret-access-key: ${{ secrets['AWS_SECRET_ACCESS_KEY_' + matrix.environment | upper] }}

      - name: Set up Docker Buildx builder
        run: |
          docker buildx create --use

      - name: Build and tag Docker image for ${{ matrix.environment }}
        run: |
          docker buildx build --file Dockerfile --tag ${{ secrets.ECR_REPOSITORY_URI }}:${{ matrix.environment }} --push .

      - name: Push image to ECR for ${{ matrix.environment }}
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ matrix.environment }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    strategy:
      matrix:
        environment: [dev, stage, prod]
    steps:
      - name: Deploy to ${{ matrix.environment }}
        run: |
          echo "Deploying to ${{ matrix.environment }}"
          # Here, you can add your deployment scripts, like ECS, EKS, or any service you use.

