name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build-push-image:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Correctly using an action

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  # Correctly using an action
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets['AWS_ACCESS_KEY_ID_' + matrix.environment | upper] }}
          aws-secret-access-key: ${{ secrets['AWS_SECRET_ACCESS_KEY_' + matrix.environment | upper] }}

      - name: Login to Amazon ECR
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v2  # Correctly using an action

      - name: Set short git commit SHA
        id: short-sha
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV  # Using run for shell command

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: 116981805219.dkr.ecr.us-east-1.amazonaws.com
          REPOSITORY: capstone-2
          IMAGE_TAG: ${{ env.COMMIT_SHORT_SHA }}  # Using environment variable set earlier
        run: |
          # Build Docker image and push in one step
          docker buildx build --file Dockerfile --tag $REGISTRY/$REPOSITORY:$IMAGE_TAG --tag $REGISTRY/$REPOSITORY:latest --push .
