name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
       - staging
       - main
jobs:
  build-push-image:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [Dev, staging, main]  # Defines the environments (Dev, staging, and main)

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Correctly using an action

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  # Correctly using an action
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v2  # Correctly using an action

      - name: Set short git commit SHA
        id: short-sha
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV  # Using run for shell command
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: 116981805219.dkr.ecr.us-east-1.amazonaws.com
          REPOSITORY: capstone-2
          IMAGE_TAG: ${{ env.COMMIT_SHORT_SHA }}-${{ matrix.environment }}

        run: |
          # Build Docker image
          docker build -t github-actions-repo .

          # Tag Docker image with commit SHA
          docker tag github-actions-repo:latest $REGISTRY/$REPOSITORY:$COMMIT_SHORT_SHA

          # Only push for the specific environment (Dev, staging, main)
          if [[ "${{ github.ref }}" == "refs/heads/Dev" ]]; then
            IMAGE_TAG=$COMMIT_SHORT_SHA-Dev
            docker tag github-actions-repo:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
            echo "Pushing image to ECR for DEV"
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            IMAGE_TAG=$COMMIT_SHORT_SHA-staging
            docker tag github-actions-repo:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
            echo "Pushing image to ECR for STAGING"
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            IMAGE_TAG=$COMMIT_SHORT_SHA-main
            docker tag github-actions-repo:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
            echo "Pushing image to ECR for MAIN"
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
            docker tag github-actions-repo:latest $REGISTRY/$REPOSITORY:latest
            echo "Pushing latest image to ECR for MAIN"
            docker push $REGISTRY/$REPOSITORY:latest
          fi